import { useState } from 'react';
import { articleById, data, keyboardEntries, pcBindings } from '../data';
import CommandKeys from './CommandKeys';
const groups = [{ title: 'チャンネル操作', categories: ['channels'] }, { title: '記録・再生', categories: ['playback'] }, { title: '画面・設定', categories: ['screens', 'settings'] }, { title: 'Effect・便利機能', categories: ['effects', 'utilities'] }];
export default function Keyboard() {
 const [selected, setSelected] = useState(keyboardEntries[0]?.key ?? ''); const entry = keyboardEntries.find(item => item.key === selected); const article = entry ? articleById.get(entry.article_id) : undefined;
 const bindingFor = (key: string) => pcBindings.find(binding => binding.eos_key.toLowerCase() === key.toLowerCase());
 return <><span className="eyebrow">KEY REFERENCE</span><h1>Eosキーボード</h1><p className="page-description">キーをタップして、役割と使い方を確認。</p><div className="keyboard-layout"><div>{groups.map(group => <section className="key-group" key={group.title}><h2>{group.title}</h2><div className="key-grid">{keyboardEntries.filter(item => group.categories.includes(articleById.get(item.article_id)?.category_id ?? '')).map(item => { const binding = bindingFor(item.key); const expanded = binding ? binding.keys.join(' + ') : ''; return <button key={item.key} aria-pressed={selected === item.key} aria-label={`${item.key}${expanded ? `（${expanded}）` : ''}`} onClick={() => setSelected(item.key)}>{item.key}{binding && <small className="pc-code">{binding.display}</small>}</button>; })}</div></section>)}</div><section id="key-description" className="detail-card key-description" aria-live="polite"><span className="eyebrow">SELECTED KEY</span><h2>{selected}</h2>{article && <><p>{article.summary}</p>{article.commands.map((command, i) => <CommandKeys key={i} command={command} />)}<a className="primary-link" href={`#${article.route}`}>「{article.title}」の記事を見る →</a></>}</section></div><section className="pc-shortcuts"><h2>{data.pc_keyboard!.display.table_title}</h2><div className="content-table-scroll"><table><thead><tr><th>Eosキー</th><th>表示コード</th><th>PC操作</th><th>内容</th></tr></thead><tbody>{pcBindings.map(binding => <tr key={binding.display}><th scope="row">{binding.eos_key}</th><td><code>{binding.display}</code></td><td>{binding.keys.join(' + ')}</td><td>{binding.purpose}</td></tr>)}</tbody></table></div></section><div className="diagram"><div><span aria-hidden="true">▦</span><p>画面図は準備中</p><small>実際のキー配置図</small></div></div></>;
}


