/* eslint-disable @typescript-eslint/no-explicit-any */
export interface Diagram { src?: string; alt: string; caption?: string }
export interface KeyboardShortcut { id?: string; label: string; platform: string; keycaps: string[]; followed_by: string[]; display: string; purpose: string; verification: string }
export interface Article { id:string; manual_section:string; chapter:number; chapter_title:string; category_id:string; title:string; route:string; theme_color:string; summary:string; when_to_use:string[]; commands:string[]; warnings:string[]; keywords:string[]; subtopics:{id:string;title:string}[]; keyboard_shortcuts?:KeyboardShortcut[]; content_sections?:ContentSection[]; steps?:string[]; diagrams?:Diagram[]; source:{manual:string;page_start:number;page_end:number;extracted_text:string}; content_status:string }
export interface HomeButton { id:string; label:string; icon:string; description:string; theme_color?:string }
export interface GuideData { source_manual:{filename:string;title:string;manual_revision:string;eos_version_noted_in_manual:string;page_count:number;publisher:string}; ui_model:{home_buttons:HomeButton[]}; chapters:{number:number;title:string;category_id:string;theme_color:string}[]; articles:Article[]; hidden_articles:Article[]; editorial_review:{merge_groups:{target_id:string;source_ids:string[]}[]; redirects?:Record<string,string>; favorite_id_migrations?:Record<string,string>}; keyboard_index:{key:string;article_id:string}[]; pc_keyboard?:{display:{table_title:string};bindings:{eos_key:string;keys:string[];display:string;article_id:string;purpose:string}[]}; }
export type TimelineField='step_time'|'in_time'|'dwell_time'|'decay_time'|'on_state'|'off_state';
export interface StepTimelineSection { type:'step_timeline';title:string;description:string;channels:number[];defaults:Record<TimelineField,number>;editable:TimelineField[];labels:Record<TimelineField,string>;phase_order:TimelineField[];axis:{label:string;unit:string};note:string;reference_image?:string }
export type ContentSection = {type:'paragraphs'|'bullets'|'steps';title:string;items:string[]}|{type:'table';title:string;columns:string[];rows:string[][]}|{type:'note';title:string;text:string;tone:string}|{type:'image';src:string;alt:string;caption?:string}|StepTimelineSection|{type:'annotated_image';src:string;alt:string;caption?:string;annotations:{kind:string;label:string;x:number;y:number;width:number;height:number}[]}|{type:'cue_timing_diagram';title?:string;delay?:number;times?:Partial<Record<'intensity_up'|'intensity_down'|'focus'|'color'|'beam',number>>}|{type:'follow_hang_diagram';title?:string;cue_time?:number;follow_time?:number;hang_time?:number}|{type:'keyboard_reference';title?:string;image:string;keys:{eos_key:string;pc_keys:string[]}[]}|{type:'cue_workflow';title:string;steps:any[]}|{type:'glossary';title:string;terms:any[]}|{type:'live_blind_comparison';title:string;modes:any[]}|{type:'offset_fan_visualizer';title:string;channels:number[];offset_modes:any[];fan:any}|{type:'submaster_visualizer';title:string;inputs:any[];rules:any[];modes:any[]}|{type:'effect_type_flow';title:string;choices:any[];prompt:string};


